" .vimrc
" load plugins
source ~/.vim/bundle/pathogen/autoload/pathogen.vim
execute pathogen#infect()

set nocompatible            " disable legacy

syntax enable
colorscheme desert
set number

set encoding=utf-8
set showcmd                 " display incomplete commands

filetype plugin indent on " load file specific plugins/indentation

" indentation
set nowrap
set tabstop=4               " set tab key to insert 2 spaces
set shiftwidth=4            " set << and >> to move 2 spaces
"set expandtab               " convert tabs to spaces
set autoindent              " use indentation of previous line
set smartindent             " indent magically
set textwidth=80            " oblige with tradition

" search
set hlsearch                " highlight search matches
set incsearch               " incremental (instant) searching
set ignorecase              " ignore case in searches
set smartcase               " ...unless mixed-case
set magic                   " greppy regexp

set laststatus=2            " always show status line

"match Error /\s\+$/          " give trailing whitespace the error highlight


" force hjkl usage
noremap <Up> ""
noremap! <Up> <Esc>
noremap <Down> ""
noremap! <Down> <Esc>
noremap <Left> ""
noremap! <Left> <Esc>
noremap <Right> ""
noremap! <Right> <Esc>

" override filetype.vim for JSON files (it thinks it's .js)
autocmd BufNewFile *.json set filetype=json

" override four tabs for javascript
autocmd Filetype jade setlocal ts=2 sw=2
autocmd Filetype js setlocal ts=2 sw=2

" highlight extraneous whitespace (ignoring current line)
autocmd BufEnter * match Error /\s\+$/
autocmd InsertEnter * match Error /\s\+\%#\@<!$/
autocmd InsertLeave * match Error /\s\+$/

let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat='pdf'

"set guioptions-=m " no menu bar
set guioptions-=T " no toolbar
set guioptions-=r " no right scroll
set guioptions-=L " no left scroll
set guifont=Terminus
