ZSH=$HOME/.oh-my-zsh

# switch zsh theme depending on hostname
case `hostname` in
    "arkady") # (bogdanov)
        ZSH_THEME="minimal"
        ;;
    "saraneth") # the binder
        ZSH_THEME="gallois"
        ;;
    "ranna") # the sleepbringer
        ZSH_THEME="arrow"
        ;;
    *)
        ZSH_THEME="gozilla"
esac

# Comment this out to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git github)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
export EDITOR=vim
