#!/bin/bash
# this file is managed by git
# github.com/zuzak/dotfiles
# vim:ts=2:et:list

hname=`hostname -s`
if [[ "$hname" == *c56* ]]
then
  # temporary delph overrides
  hname="delph"
fi

if [[ "$hname" == *HOD* ]]
then
  hname="mac"
  export PYTHONPATH="$HOME/local/lib/python2.7/site-packages"
  export PATH="$PATH:$PYTHONPATH"
  test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
  alias ls="ls -G"
else
    alias ls="ls --color"
fi

if [ -f "/etc/redhat=release" ]; then
  alias apt-get='yum'
fi

if [[ "$hname" == saxifrage ]]
then
  if [[ -z $DISPLAY ]] && [[ $(tty) = /dev/tty1 ]]; then
    startx
  fi
  alias za="zathura --fork"
fi


if [[ `whoami` == vagrant ]]
then
  export PS1="\[\e[00;34m\]\H\[\e[0m\]\[\e[00;37m\] \[\e[0m\]\[\e[00;32m\]\w>\[\e[0m\] "
fi

export TERM="xterm" # nothing plays well with st

# force utf8
export LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8

export PAGER=/usr/bin/less
export EDITOR="vim"
alias xyzzy="echo A hollow voice says \'Fool.\'"
alias jgo="clear && javac *.java && java"
alias style="php ~/git/code-utils/stylize.php "
alias nao="ssh nethack@alt.org"

# append, not overwrite
shopt -s histappend
shopt -s cmdhist
HISTFILESIZE=1000000
HISTSIZE=1000000
HISTTIMEFORMAT='%F %T '
# Change the file location because certain bash sessions truncate .bash_history file upon close.
# http://superuser.com/questions/575479/bash-history-truncated-to-500-lines-on-each-login
export HISTFILE=~/.bash_eternal_history
# Force prompt to write history after every command.
# http://superuser.com/questions/20900/bash-history-loss
PROMPT_COMMAND='history -a'


PATH=~/bin:$PATH

export GPG_TTY=$(tty) # sometimes this isn't automatically set

if [[ "$hname" == saraneth ]]
then
  export PS1="\[\e[00;33m\]$hname \[\e[0m\]\[\e[32;1m\]\w> \[\e[0m\]"
  if [[ `screen -ls | grep irc | grep Detached` ]]
  then
    screen -dr irc
  fi
else
  export PS1="\[\e[36;1m\]$hname \[\e[32;1m\]\w> \[\e[0m\]"
fi

alias nodejs="node"


